// North-East India state and district registry for emergency backup location dispatch
export const nerLocations: Record<string, string[]> = {
  "Arunachal Pradesh": [
    "Tawang",
    "West Kameng",
    "East Kameng",
    "Papum Pare",
    "West Siang",
    "East Siang",
    "Upper Siang",
    "Lower Subansiri",
    "Upper Subansiri",
    "Changlang",
    "Tirap",
    "Anjaw",
    "Kurung Kumey",
    "Dibang Valley",
    "Lower Dibang Valley",
    "Lohit",
    "Namsai",
    "Shi Yomi",
    "Pakke Kessang",
    "Kamle",
  ],
  "Assam": [
    "Dima Hasao (Haflong)",
    "Karbi Anglong",
    "West Karbi Anglong",
    "Kamrup Metropolitan (Guwahati)",
    "Kamrup",
    "Cachar (Silchar)",
    "Hailakandi",
    "Karimganj",
    "Dibrugarh",
    "Jorhat",
    "Tinsukia",
    "Sonitpur (Tezpur)",
    "Golaghat",
    "Nagaon",
    "Sivasagar",
    "Bongaigaon",
    "Kokrajhar",
    "Dhubri",
    "Goalpara",
  ],
  "Manipur": [
    "Imphal West",
    "Imphal East",
    "Ukhrul",
    "Churachandpur",
    "Senapati",
    "Tamenglong",
    "Chandel",
    "Bishnupur",
    "Thoubal",
    "Kangpokpi",
    "Noney",
    "Tengnoupal",
    "Kamjong",
  ],
  "Meghalaya": [
    "East Khasi Hills (Shillong)",
    "West Khasi Hills",
    "South West Khasi Hills",
    "Ri-Bhoi (Nongpoh)",
    "West Garo Hills (Tura)",
    "East Garo Hills",
    "South Garo Hills",
    "North Garo Hills",
    "West Jaintia Hills (Jowai)",
    "East Jaintia Hills (Khliehriat)",
  ],
  "Mizoram": [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Kolasib",
    "Serchhip",
    "Lawngtlai",
    "Mamit",
    "Saiha",
    "Hnahthial",
    "Khawzawl",
    "Saitual",
  ],
  "Nagaland": [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Mon",
    "Phek",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Kiphire",
    "Longleng",
    "Peren",
    "Chümoukedima",
  ],
  "Sikkim": [
    "Gangtok",
    "Namchi",
    "Mangan (North Sikkim)",
    "Gyalshing (West Sikkim)",
    "Pakyong",
    "Soreng",
  ],
  "Tripura": [
    "West Tripura (Agartala)",
    "Gomati (Udaipur)",
    "South Tripura",
    "North Tripura",
    "Dhalai (Ambassa)",
    "Unakoti (Kailashahar)",
    "Khowai",
    "Sepahijala",
  ],
};

export const nerStateList = Object.keys(nerLocations);
